"""drivers, deliver integration and logistics

Revision ID: 0fb735a539b3
Revises: 20260907_driver_logistics
Create Date: 2026-09-07 17:25:37.791262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers.
revision = '0fb735a539b3'
down_revision = '20260907_driver_logistics'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('brands_slug_key'), 'brands', type_='unique')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.drop_constraint(op.f('cart_items_user_id_product_id_variant_id_key'), 'cart_items', type_='unique')
    op.create_unique_constraint('unique_cart_item', 'cart_items', ['user_id', 'product_id', 'variant_id'])
    op.drop_constraint(op.f('categories_slug_key'), 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.alter_column('demand_alerts', 'notified_vendors',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_constraint(op.f('orders_order_number_key'), 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.drop_constraint(op.f('products_sku_key'), 'products', type_='unique')
    op.drop_constraint(op.f('products_slug_key'), 'products', type_='unique')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.drop_constraint(op.f('promo_codes_code_key'), 'promo_codes', type_='unique')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_index(op.f('ix_quotation_line_items_quotation_id'), 'quotation_line_items', ['quotation_id'], unique=False)
    op.drop_index(op.f('ix_token_transactions_created_at'), table_name='token_transactions')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_phone_number_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=True)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.alter_column('vendor_verification_tiers', 'required_document_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('vendor_verification_tiers', 'perks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(op.f('vendor_verification_tiers_tier_code_key'), 'vendor_verification_tiers', type_='unique')
    op.drop_index(op.f('ix_vendor_verification_tiers_tier_code'), table_name='vendor_verification_tiers')
    op.create_index(op.f('ix_vendor_verification_tiers_tier_code'), 'vendor_verification_tiers', ['tier_code'], unique=True)
    op.alter_column('vendors', 'specializations',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'specializations',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index(op.f('ix_vendor_verification_tiers_tier_code'), table_name='vendor_verification_tiers')
    op.create_index(op.f('ix_vendor_verification_tiers_tier_code'), 'vendor_verification_tiers', ['tier_code'], unique=False)
    op.create_unique_constraint(op.f('vendor_verification_tiers_tier_code_key'), 'vendor_verification_tiers', ['tier_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('vendor_verification_tiers', 'perks',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('vendor_verification_tiers', 'required_document_types',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_phone_number_key'), 'users', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_token_transactions_created_at'), 'token_transactions', ['created_at'], unique=False)
    op.drop_index(op.f('ix_quotation_line_items_quotation_id'), table_name='quotation_line_items')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=False)
    op.create_unique_constraint(op.f('promo_codes_code_key'), 'promo_codes', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_unique_constraint(op.f('products_slug_key'), 'products', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('products_sku_key'), 'products', ['sku'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
    op.create_unique_constraint(op.f('orders_order_number_key'), 'orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('demand_alerts', 'notified_vendors',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_unique_constraint(op.f('categories_slug_key'), 'categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('unique_cart_item', 'cart_items', type_='unique')
    op.create_unique_constraint(op.f('cart_items_user_id_product_id_variant_id_key'), 'cart_items', ['user_id', 'product_id', 'variant_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=False)
    op.create_unique_constraint(op.f('brands_slug_key'), 'brands', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###