"""not initial

Revision ID: 13b65519c4ad
Revises: 9745041a2196
Create Date: 2026-07-22 07:54:50.829115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '13b65519c4ad'
down_revision = '9745041a2196'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###