"""5th july payment and orders

Revision ID: 1994792eaacf
Revises: dc0a4de98bc5
Create Date: 2026-07-05 15:42:07.748335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '1994792eaacf'
down_revision = 'dc0a4de98bc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###