"""11th July BOQ updates 837 dot

Revision ID: 1fef81abedd9
Revises: f88d97b9bfad
Create Date: 2026-07-11 08:38:11.959056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '1fef81abedd9'
down_revision = 'f88d97b9bfad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###