"""5th july update driver details

Revision ID: 27d541d43412
Revises: 1994792eaacf
Create Date: 2026-07-05 22:11:10.265634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '27d541d43412'
down_revision = '1994792eaacf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('driver_name', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('driver_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'driver_phone')
    op.drop_column('orders', 'driver_name')
    # ### end Alembic commands ###