"""4th july added address, city and state to vendor data

Revision ID: 38076f762104
Revises: 978daf55cdc8
Create Date: 2026-07-04 18:19:54.834392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '38076f762104'
down_revision = '978daf55cdc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###