"""onboard vendors 12Aug

Revision ID: 382e0bc5073b
Revises: 74c4a6221376
Create Date: 2026-08-13 19:44:52.523750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '382e0bc5073b'
down_revision = '74c4a6221376'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_verification_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier_code', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('transaction_cap', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('required_document_types', sa.JSON(), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=True),
    sa.Column('perks', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_verification_tiers_tier_code'), 'vendor_verification_tiers', ['tier_code'], unique=True)
    op.add_column('vendor_documents', sa.Column('tier', sa.String(length=20), nullable=True))
    op.add_column('vendor_documents', sa.Column('review_status', sa.String(length=20), nullable=True))
    op.add_column('vendor_documents', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('vendor_documents', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'vendor_documents', 'users', ['reviewed_by'], ['id'])
    op.add_column('vendors', sa.Column('verification_tier', sa.String(length=20), nullable=False, server_default=sa.text("'cac_only'")))
    op.add_column('vendors', sa.Column('transaction_volume', sa.Numeric(precision=15, scale=2), nullable=True, server_default=sa.text("0.00")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'transaction_volume')
    op.drop_column('vendors', 'verification_tier')
    op.drop_constraint(None, 'vendor_documents', type_='foreignkey')
    op.drop_column('vendor_documents', 'reviewed_at')
    op.drop_column('vendor_documents', 'reviewed_by')
    op.drop_column('vendor_documents', 'review_status')
    op.drop_column('vendor_documents', 'tier')
    op.drop_index(op.f('ix_vendor_verification_tiers_tier_code'), table_name='vendor_verification_tiers')
    op.drop_table('vendor_verification_tiers')
    # ### end Alembic commands ###