"""db update 3

Revision ID: 39c65c004c14
Revises: 74b5cdef71a2
Create Date: 2026-07-02 17:34:42.386250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '39c65c004c14'
down_revision = '74b5cdef71a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('cac_business_registration_number', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('vendors_business_registration_number_key'), 'vendors', type_='unique')
    op.create_unique_constraint(None, 'vendors', ['cac_business_registration_number'])
    op.drop_column('vendors', 'business_registration_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('business_registration_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vendors', type_='unique')
    op.create_unique_constraint(op.f('vendors_business_registration_number_key'), 'vendors', ['business_registration_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('vendors', 'cac_business_registration_number')
    # ### end Alembic commands ###