"""4th july added accounts vendor data

Revision ID: 3baebbf3e52e
Revises: 38076f762104
Create Date: 2026-07-04 18:27:46.856417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '3baebbf3e52e'
down_revision = '38076f762104'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('business_address', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('vendors_user_id_key'), 'vendors', type_='unique')
    op.drop_constraint(op.f('vendors_user_id_fkey'), 'vendors', type_='foreignkey')
    op.drop_column('vendors', 'business_type')
    op.drop_column('vendors', 'user_id')
    op.drop_column('vendors', 'business_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('business_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('vendors', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('vendors', sa.Column('business_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('vendors_user_id_fkey'), 'vendors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('vendors_user_id_key'), 'vendors', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('vendors', 'business_address')
    # ### end Alembic commands ###