"""15th July demands, drop bank details

Revision ID: 43a5d3c33488
Revises: a9c9cd13f49b
Create Date: 2026-07-15 22:27:12.359125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers.
revision = '43a5d3c33488'
down_revision = 'a9c9cd13f49b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demand_alerts', 'notified_vendors',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index(op.f('idx_demand_alerts_city'), table_name='demand_alerts')
    op.drop_index(op.f('idx_demand_alerts_requested_by'), table_name='demand_alerts')
    op.drop_index(op.f('idx_demand_alerts_status'), table_name='demand_alerts')
    op.alter_column('promo_codes', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('promo_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('promo_codes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('promo_codes_code_key'), 'promo_codes', type_='unique')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.drop_constraint(op.f('shipping_zone_mappings_origin_state_origin_city_destination_key'), 'shipping_zone_mappings', type_='unique')
    op.alter_column('vendor_addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_bank_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('vendor_documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('vendor_shipping_overrides_vendor_id_zone_id_key'), 'vendor_shipping_overrides', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('vendor_shipping_overrides_vendor_id_zone_id_key'), 'vendor_shipping_overrides', ['vendor_id', 'zone_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('vendor_documents', 'uploaded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_bank_accounts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('vendor_addresses', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('shipping_zone_mappings_origin_state_origin_city_destination_key'), 'shipping_zone_mappings', ['origin_state', 'origin_city', 'destination_state', 'destination_city'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=False)
    op.create_unique_constraint(op.f('promo_codes_code_key'), 'promo_codes', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('promo_codes', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('promo_codes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('promo_codes', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('idx_demand_alerts_status'), 'demand_alerts', ['status'], unique=False)
    op.create_index(op.f('idx_demand_alerts_requested_by'), 'demand_alerts', ['requested_by'], unique=False)
    op.create_index(op.f('idx_demand_alerts_city'), 'demand_alerts', ['city'], unique=False)
    op.alter_column('demand_alerts', 'notified_vendors',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    # ### end Alembic commands ###