"""4th july migrations

Revision ID: 5b66c88dffa0
Revises: 39c65c004c14
Create Date: 2026-07-04 14:28:28.265919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers.
revision = '5b66c88dffa0'
down_revision = '39c65c004c14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_reviews_product_id'), 'product_reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_reviews_user_id'), 'product_reviews', ['user_id'], unique=False)
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_products_brand_name'), table_name='products')
    op.drop_column('products', 'brand_name')
    # Create the enum types first
    sa.Enum('customer', 'vendor', 'admin', 'super_admin', name='user_role').create(op.get_bind())
    sa.Enum('active', 'suspended', 'pending_verification', 'deactivated', name='user_status').create(op.get_bind())

    # Alter columns to use the native enum types with USING clause to cast existing data
    # Note: lower() is needed because existing data has uppercase values like "VENDOR" (Python enum member names)
    # but the new enum type only accepts lowercase values like "vendor"
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('customer', 'vendor', 'admin', 'super_admin', name='user_role', create_type=False),
               postgresql_using='lower(role::text)::user_role',
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('active', 'suspended', 'pending_verification', 'deactivated', name='user_status', create_type=False),
               postgresql_using='lower(status::text)::user_status',
               existing_nullable=False)
    op.alter_column('vendors', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.Enum('active', 'suspended', 'pending_verification', 'deactivated', name='user_status', create_type=False),
               type_=sa.VARCHAR(length=30),
               postgresql_using='status::text',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('customer', 'vendor', 'admin', 'super_admin', name='user_role', create_type=False),
               type_=sa.VARCHAR(length=20),
               postgresql_using='role::text',
               existing_nullable=False)
    sa.Enum(name='user_role').drop(op.get_bind())
    sa.Enum(name='user_status').drop(op.get_bind())
    op.add_column('products', sa.Column('brand_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_products_brand_name'), 'products', ['brand_name'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reviewer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('reviews_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reviews_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('reviews_pkey'))
    )
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.drop_index(op.f('ix_product_reviews_user_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_product_id'), table_name='product_reviews')
    op.drop_table('product_reviews')
    # ### end Alembic commands ###