"""4th july added accounts vendor datata

Revision ID: 70df625fdcba
Revises: 3baebbf3e52e
Create Date: 2026-07-04 18:31:52.366261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '70df625fdcba'
down_revision = '3baebbf3e52e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('vendors', sa.Column('business_name', sa.String(length=255), nullable=False))
    op.add_column('vendors', sa.Column('business_type', sa.String(length=255), nullable=False))
    op.add_column('vendors', sa.Column('city', sa.String(length=255), nullable=False))
    op.add_column('vendors', sa.Column('state', sa.String(length=255), nullable=False))
    op.add_column('vendors', sa.Column('bank_account_number', sa.String(length=255), nullable=False))
    op.add_column('vendors', sa.Column('bank_account_name', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'vendors', ['user_id'])
    op.create_foreign_key(None, 'vendors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.drop_constraint(None, 'vendors', type_='unique')
    op.drop_column('vendors', 'bank_account_name')
    op.drop_column('vendors', 'bank_account_number')
    op.drop_column('vendors', 'state')
    op.drop_column('vendors', 'city')
    op.drop_column('vendors', 'business_type')
    op.drop_column('vendors', 'business_name')
    op.drop_column('vendors', 'user_id')
    # ### end Alembic commands ###