"""10th BOQ updates

Revision ID: 72752edc4a65
Revises: 41856507443e
Create Date: 2026-07-10 10:07:59.450339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '72752edc4a65'
down_revision = '41856507443e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###