"""db update 2

Revision ID: 74b5cdef71a2
Revises: 8f1d2cbe8a62
Create Date: 2026-07-02 16:45:09.335493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '74b5cdef71a2'
down_revision = '8f1d2cbe8a62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('business_registration_number', sa.String(length=100), nullable=True))
    op.alter_column('vendors', 'tax_identification_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_unique_constraint(None, 'vendors', ['business_registration_number'])
    op.drop_column('vendors', 'cac_certificate')
    op.drop_column('vendors', 'cac_business_registration_number')
    op.drop_column('vendors', 'utility_bill')
    op.drop_column('vendors', 'bank_account_name')
    op.drop_column('vendors', 'bank_account_number')
    op.drop_column('vendors', 'business_license')
    op.drop_column('vendors', 'bank_name')
    op.drop_column('vendors', 'business_address')
    op.drop_column('vendors', 'tax_clearance')
    op.drop_column('vendors', 'city')
    op.drop_column('vendors', 'state')
    op.drop_column('vendors', 'business_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('business_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('tax_clearance', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('business_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('vendors', sa.Column('business_license', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('bank_account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('vendors', sa.Column('bank_account_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('vendors', sa.Column('utility_bill', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('cac_business_registration_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('cac_certificate', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vendors', type_='unique')
    op.alter_column('vendors', 'tax_identification_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('vendors', 'business_registration_number')
    # ### end Alembic commands ###