"""admin related updates

Revision ID: 74c4a6221376
Revises: 20260809_audit_roles
Create Date: 2026-08-10 20:27:05.737407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '74c4a6221376'
down_revision = '20260809_audit_roles'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###