"""Initial migrations

Revision ID: 771b5f60cf56
Revises: cf5fb93b9746
Create Date: 2026-07-02 11:27:59.749316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '771b5f60cf56'
down_revision = 'cf5fb93b9746'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###