"""15th July updates

Revision ID: 810eb4470d40
Revises: c0dbb09b0a77
Create Date: 2026-07-15 14:53:11.808813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '810eb4470d40'
down_revision = 'c0dbb09b0a77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###