"""7th July Alembic-Aiven Initial Migration

Revision ID: 83e7282dd87a
Revises: 9c79efc52636
Create Date: 2026-07-07 11:36:47.344678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '83e7282dd87a'
down_revision = '9c79efc52636'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###