"""db update

Revision ID: 8f1d2cbe8a62
Revises: 771b5f60cf56
Create Date: 2026-07-02 16:18:47.730640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '8f1d2cbe8a62'
down_revision = '771b5f60cf56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('specification', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('previous_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('lga', sa.String(length=100), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('trend', sa.Enum('UP', 'DOWN', 'STABLE', name='pricetrend', native_enum=False, length=10), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_rates_category_id'), 'material_rates', ['category_id'], unique=False)
    op.create_index(op.f('ix_material_rates_state'), 'material_rates', ['state'], unique=False)
    op.create_table('material_rate_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rate_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['rate_id'], ['material_rates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_rate_history_rate_id'), 'material_rate_history', ['rate_id'], unique=False)
    op.add_column('categories', sa.Column('division', sa.String(length=100), nullable=True))
    op.add_column('categories', sa.Column('material_type', sa.String(length=50), nullable=True))
    op.add_column('categories', sa.Column('default_unit', sa.String(length=50), nullable=True))
    op.add_column('categories', sa.Column('waste_factor', sa.Numeric(precision=5, scale=2), nullable=True))
    op.create_index(op.f('ix_categories_division'), 'categories', ['division'], unique=False)
    op.add_column('products', sa.Column('brand_name', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.create_index(op.f('ix_products_brand_name'), 'products', ['brand_name'], unique=False)
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_products_brand_name'), table_name='products')
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.drop_column('products', 'brand_name')
    op.drop_index(op.f('ix_categories_division'), table_name='categories')
    op.drop_column('categories', 'waste_factor')
    op.drop_column('categories', 'default_unit')
    op.drop_column('categories', 'material_type')
    op.drop_column('categories', 'division')
    op.drop_index(op.f('ix_material_rate_history_rate_id'), table_name='material_rate_history')
    op.drop_table('material_rate_history')
    op.drop_index(op.f('ix_material_rates_state'), table_name='material_rates')
    op.drop_index(op.f('ix_material_rates_category_id'), table_name='material_rates')
    op.drop_table('material_rates')
    # ### end Alembic commands ###