"""4th july added business_type column

Revision ID: 978daf55cdc8
Revises: 5b66c88dffa0
Create Date: 2026-07-04 18:09:25.652567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '978daf55cdc8'
down_revision = '5b66c88dffa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('business_type', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'business_type')
    # ### end Alembic commands ###