"""6th july product details shipping and delivery date update

Revision ID: 9c79efc52636
Revises: 27d541d43412
Create Date: 2026-07-06 10:36:03.038680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = '9c79efc52636'
down_revision = '27d541d43412'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('shipping_fee', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('products', sa.Column('estimated_delivery_days', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('free_shipping_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'free_shipping_threshold')
    op.drop_column('products', 'estimated_delivery_days')
    op.drop_column('products', 'shipping_fee')
    # ### end Alembic commands ###