"""15th July demands, shipping tables

Revision ID: a9c9cd13f49b
Revises: c0dbb09b0a78
Create Date: 2026-07-15 20:07:16.280496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers.
revision = 'a9c9cd13f49b'
down_revision = 'c0dbb09b0a78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Transaction type enum (idempotent)
    op.execute("DO $$ BEGIN CREATE TYPE transactiontype AS ENUM ('purchase', 'consumption', 'refund', 'free_tier', 'expiry'); EXCEPTION WHEN duplicate_object THEN NULL; END $$")

    # All tables use IF NOT EXISTS to be idempotent
    op.execute("CREATE TABLE IF NOT EXISTS token_transactions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, transaction_type transactiontype NOT NULL, amount INTEGER NOT NULL, balance_after INTEGER NOT NULL, action_type VARCHAR(50), boq_id VARCHAR(50), reference VARCHAR(100), description VARCHAR(255), created_at TIMESTAMPTZ DEFAULT NOW())")
    op.execute("CREATE INDEX IF NOT EXISTS ix_token_transactions_user_id ON token_transactions (user_id)")

    op.execute("CREATE TABLE IF NOT EXISTS token_usage (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, balance INTEGER NOT NULL DEFAULT 0, lifetime_purchased INTEGER NOT NULL DEFAULT 0, lifetime_consumed INTEGER NOT NULL DEFAULT 0, free_tier_used_this_month INTEGER NOT NULL DEFAULT 0, free_tier_month VARCHAR(7), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())")
    op.execute("CREATE INDEX IF NOT EXISTS ix_token_usage_user_id ON token_usage (user_id)")

    op.execute("CREATE TABLE IF NOT EXISTS promo_codes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(50) UNIQUE NOT NULL, description TEXT, discount_percent DECIMAL(5,2) NOT NULL, max_uses INTEGER DEFAULT 0, current_uses INTEGER DEFAULT 0, min_order_amount DECIMAL(15,2) DEFAULT 0, is_active BOOLEAN DEFAULT TRUE, vendor_id UUID REFERENCES vendors(id) ON DELETE CASCADE, expires_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())")
    op.execute("CREATE INDEX IF NOT EXISTS ix_promo_codes_code ON promo_codes (code)")

    op.execute("CREATE TABLE IF NOT EXISTS vendor_addresses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id UUID NOT NULL REFERENCES vendors(id) ON DELETE CASCADE, address_type VARCHAR(20) NOT NULL, address_line1 TEXT NOT NULL, address_line2 TEXT, city VARCHAR(100) NOT NULL, state VARCHAR(100) NOT NULL, lga VARCHAR(100), postal_code VARCHAR(20), landmark TEXT, latitude DECIMAL(10,8), longitude DECIMAL(11,8), is_primary BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW())")

    op.execute("CREATE TABLE IF NOT EXISTS vendor_bank_accounts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id UUID NOT NULL REFERENCES vendors(id) ON DELETE CASCADE, bank_name VARCHAR(100) NOT NULL, account_number VARCHAR(20) NOT NULL, account_name VARCHAR(255) NOT NULL, bank_code VARCHAR(10), is_primary BOOLEAN DEFAULT FALSE, verified BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW())")

    op.execute("CREATE TABLE IF NOT EXISTS vendor_documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id UUID NOT NULL REFERENCES vendors(id) ON DELETE CASCADE, document_type VARCHAR(50) NOT NULL, document_url TEXT NOT NULL, uploaded_at TIMESTAMPTZ DEFAULT NOW(), verified BOOLEAN DEFAULT FALSE)")

    # Drop old indexes (safe with IF EXISTS)
    op.execute("DROP INDEX IF EXISTS ix_demand_alerts_city")
    op.execute("DROP INDEX IF EXISTS ix_demand_alerts_requested_by")
    op.execute("DROP INDEX IF EXISTS ix_demand_alerts_status")
    # Create standard indexes
    op.execute("CREATE INDEX IF NOT EXISTS ix_demand_alerts_city ON demand_alerts (city)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_demand_alerts_requested_by ON demand_alerts (requested_by)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_demand_alerts_status ON demand_alerts (status)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('vendor_shipping_overrides_vendor_id_zone_id_key'), 'vendor_shipping_overrides', ['vendor_id', 'zone_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('shipping_zone_mappings_origin_state_origin_city_destination_key'), 'shipping_zone_mappings', ['origin_state', 'origin_city', 'destination_state', 'destination_city'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_demand_alerts_status'), table_name='demand_alerts')
    op.drop_index(op.f('ix_demand_alerts_requested_by'), table_name='demand_alerts')
    op.drop_index(op.f('ix_demand_alerts_city'), table_name='demand_alerts')
    op.create_index(op.f('idx_demand_alerts_status'), 'demand_alerts', ['status'], unique=False)
    op.create_index(op.f('idx_demand_alerts_requested_by'), 'demand_alerts', ['requested_by'], unique=False)
    op.create_index(op.f('idx_demand_alerts_city'), 'demand_alerts', ['city'], unique=False)
    op.alter_column('demand_alerts', 'notified_vendors',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_table('vendor_documents')
    op.drop_table('vendor_bank_accounts')
    op.drop_table('vendor_addresses')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_token_usage_user_id'), table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index(op.f('ix_token_transactions_user_id'), table_name='token_transactions')
    op.drop_table('token_transactions')
    # ### end Alembic commands ###