"""16th July updates.

Revision ID: bc0d9a88cc3a
Revises: d73761d596a2
Create Date: 2026-07-16 10:37:27.628473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers.
revision = 'bc0d9a88cc3a'
down_revision = 'd73761d596a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_drafts_user_id'), table_name='vendor_drafts')
    op.drop_table('vendor_drafts')
    op.add_column('vendors', sa.Column('delivery_time', sa.String(length=100), nullable=True))
    op.add_column('vendors', sa.Column('specializations', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('vendors', 'business_image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'business_image',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('vendors', 'specializations')
    op.drop_column('vendors', 'delivery_time')
    op.create_table('vendor_drafts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.VARCHAR(length=50), server_default=sa.text("'business-info'::character varying"), autoincrement=False, nullable=True),
    sa.Column('business_info', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('banking_info', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vendor_drafts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vendor_drafts_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('vendor_drafts_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_vendor_drafts_user_id'), 'vendor_drafts', ['user_id'], unique=False)
    # ### end Alembic commands ###