"""10th BOQ updates 3pm dot

Revision ID: bd8400a8a24b
Revises: 72752edc4a65
Create Date: 2026-07-10 15:01:24.395630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = 'bd8400a8a24b'
down_revision = '72752edc4a65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###