"""15th July demands table

Revision ID: bde771659014
Revises: 810eb4470d40
Create Date: 2026-07-15 16:15:55.286883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = 'bde771659014'
down_revision = '810eb4470d40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###