"""15th July updates

Revision ID: c0dbb09b0a77
Revises: 1fef81abedd9
Create Date: 2026-07-15 14:52:21.355174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = 'c0dbb09b0a77'
down_revision = '1fef81abedd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('platform_margin', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'platform_margin')
    # ### end Alembic commands ###