"""4th july added bank name

Revision ID: d2d09d753121
Revises: 70df625fdcba
Create Date: 2026-07-05 01:30:00.468409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = 'd2d09d753121'
down_revision = '70df625fdcba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('bank_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'bank_name')
    # ### end Alembic commands ###