"""5th july payment and orders

Revision ID: dc0a4de98bc5
Revises: d2d09d753121
Create Date: 2026-07-05 15:41:01.146142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = 'dc0a4de98bc5'
down_revision = 'd2d09d753121'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###