"""10th BOQ updates 9pm not dot

Revision ID: f88d97b9bfad
Revises: bd8400a8a24b
Create Date: 2026-07-10 21:19:22.187098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers.
revision = 'f88d97b9bfad'
down_revision = 'bd8400a8a24b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###