"""
Fraud detection models — power the Fraud Detection admin pages (Phase 3).
"""
from sqlalchemy import (
    Column, String, DateTime, Numeric, Integer, Boolean, ForeignKey, Text, Index
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from app.core.database import Base


class FraudAlert(Base):
    """A fraud / risk alert generated by the monitoring engine."""
    __tablename__ = "fraud_alerts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    alert_number = Column(String(50), unique=True, nullable=False, index=True)
    alert_type = Column(String(100), nullable=False)      # Suspicious Pattern, Payment Anomaly, etc.
    severity = Column(String(20), default="medium")      # low / medium / high / critical
    description = Column(Text)
    risk_score = Column(Integer, default=0)
    amount = Column(Numeric(15, 2), default=0)
    status = Column(String(50), default="under_review")  # under_review / cleared / blocked
    detected_at = Column(DateTime, default=datetime.utcnow, index=True)
    resolved_at = Column(DateTime)
    resolved_by = Column(String(100))
    is_negotiation = Column(Boolean, default=False)      # True for negotiation-fraud alerts

    accounts = relationship(
        "FraudAlertAccount",
        back_populates="alert",
        cascade="all, delete-orphan",
    )
    transactions = relationship(
        "FraudAlertTransaction",
        back_populates="alert",
        cascade="all, delete-orphan",
    )

    __table_args__ = (
        Index("ix_fraud_alerts_status_severity", "status", "severity"),
    )

    def __repr__(self):
        return f"<FraudAlert {self.alert_number} {self.severity}>"


class FraudAlertAccount(Base):
    """A user account implicated in a fraud alert."""
    __tablename__ = "fraud_alert_accounts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    alert_id = Column(UUID(as_uuid=True), ForeignKey("fraud_alerts.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    account_id = Column(String(50))    # external display id
    account_name = Column(String(255))
    account_email = Column(String(255))
    created_at = Column(DateTime, default=datetime.utcnow)

    alert = relationship("FraudAlert", back_populates="accounts")


class FraudAlertTransaction(Base):
    """A flagged transaction in a fraud alert."""
    __tablename__ = "fraud_alert_transactions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    alert_id = Column(UUID(as_uuid=True), ForeignKey("fraud_alerts.id", ondelete="CASCADE"), nullable=False, index=True)
    transaction_id = Column(String(50))
    amount = Column(Numeric(15, 2), default=0)
    created_at = Column(DateTime, default=datetime.utcnow)

    alert = relationship("FraudAlert", back_populates="transactions")